"""Bingo card generation service."""

from typing import List, Dict
from f1bot.services.llm import generate_bingo_meme_events


def generate_bingo_cells(race: Dict, context: Dict, lang: str) -> List[Dict]:
    """Generate 16 bingo cells (10-12 hard + 4-6 meme)."""
    # Hard checkable events (10-12) - multilingual
    if lang == "ru":
        hard_events = [
            {"id": "safety_car", "title": "Safety Car", "type": "hard"},
            {"id": "dnf", "title": "DNF", "type": "hard"},
            {"id": "fastest_lap", "title": "Быстрейший круг", "type": "hard"},
            {"id": "pit_under_sc", "title": "Пит-стоп под SC", "type": "hard"},
            {"id": "team_radio_controversy", "title": "Скандал в радио", "type": "hard"},
            {"id": "overtake", "title": "Зрелищный обгон", "type": "hard"},
            {"id": "penalty", "title": "Штраф", "type": "hard"},
            {"id": "red_flag", "title": "Красный флаг", "type": "hard"},
            {"id": "pit_stop_mistake", "title": "Ошибка в пит-стопе", "type": "hard"},
            {"id": "crash", "title": "Авария", "type": "hard"},
            {"id": "strategy_masterclass", "title": "Мастер-класс стратегии", "type": "hard"},
            {"id": "last_lap_drama", "title": "Драма на последнем круге", "type": "hard"},
        ]
    else:
        hard_events = [
            {"id": "safety_car", "title": "Safety Car", "type": "hard"},
            {"id": "dnf", "title": "DNF", "type": "hard"},
            {"id": "fastest_lap", "title": "Fastest Lap", "type": "hard"},
            {"id": "pit_under_sc", "title": "Pit under SC", "type": "hard"},
            {"id": "team_radio_controversy", "title": "Team Radio Controversy", "type": "hard"},
            {"id": "overtake", "title": "Spectacular Overtake", "type": "hard"},
            {"id": "penalty", "title": "Penalty", "type": "hard"},
            {"id": "red_flag", "title": "Red Flag", "type": "hard"},
            {"id": "pit_stop_mistake", "title": "Pit Stop Mistake", "type": "hard"},
            {"id": "crash", "title": "Crash", "type": "hard"},
            {"id": "strategy_masterclass", "title": "Strategy Masterclass", "type": "hard"},
            {"id": "last_lap_drama", "title": "Last Lap Drama", "type": "hard"},
        ]
    
    # Meme events (4-6) - generated by LLM
    meme_events = generate_bingo_meme_events(race, context, lang)
    
    # Combine: take 12 hard events and 4 meme events to get exactly 16
    cells = hard_events[:12] + meme_events[:4]
    
    return cells[:16]  # Ensure exactly 16
